spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/CloserWU/spring-cloud-config
          search-paths: spring-cloud-config
          username: CloserWU
          password: ws995339251

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/